### Testing
devtools::document()
devtools::load_all()
data("kva")
fit1 <- streg(Surv(failtime, event) ~ load + bearings, data = kva, distribution = "exp", x = TRUE)
predict.streg(fit1, type = "s")
fit2 <- streg(Surv(failtime, event) ~ load + bearings, data = kva, distribution = "wei", x = TRUE)
predict.streg(fit2, type = "s")
fit3 <- streg(Surv(failtime, event) ~ load + bearings, data = kva, distribution = "gom", x = TRUE)
predict.streg(fit3, type = "s")
