data("cancer", package = "streg")
f1 <- streg::streg(survival::Surv(studytime, died) ~ 1, data = cancer, distribution = "exp")
f2 <- streg::streg(survival::Surv(studytime, died) ~ drug * age, data = cancer, distribution = "exp")

testthat::test_that("S3 method: coef", {
  testthat::expect_equal(object = coef(f1), expected = coef(summary(f1)))
  testthat::expect_length(object = coef(f1), n = 1)
  testthat::expect_length(object = coef(summary(f1)), n = 1)
  testthat::expect_named(object = coef(f1))
  testthat::expect_named(object = coef(summary(f1)))
  testthat::expect_type(object = coef(f1), "double")
  testthat::expect_type(object = coef(summary(f1)), "double")

  testthat::expect_length(object = coef(f2), n = 1 + 3)
  testthat::expect_length(object = coef(summary(f2)), n = 1 + 3)
  testthat::expect_named(object = coef(f2))
  testthat::expect_named(object = coef(summary(f2)))
  testthat::expect_type(object = coef(f2), "double")
  testthat::expect_type(object = coef(summary(f2)), "double")
})

testthat::test_that("S3 method: vcov", {
  testthat::expect_equal(object = vcov(f1), expected = vcov(summary(f1)))
  testthat::expect_equal(object = nrow(vcov(f1)), expected = nrow(vcov(summary(f1))))
  testthat::expect_equal(object = ncol(vcov(f1)), expected = ncol(vcov(summary(f1))))
  testthat::expect_equal(object = nrow(vcov(f1)), expected = ncol(vcov(f1)))
  testthat::expect_equal(object = nrow(vcov(summary(f1))), expected = ncol(vcov(summary(f1))))
  testthat::expect_false(object = is.null(row.names(vcov(f1))))
  testthat::expect_false(object = is.null(colnames(vcov(f1))))
  testthat::expect_false(object = is.null(row.names(vcov(summary(f1)))))
  testthat::expect_false(object = is.null(colnames(vcov(summary(f1)))))
  testthat::expect_type(object = vcov(f1), type = "double")
  testthat::expect_type(object = vcov(summary(f1)), type = "double")

  testthat::expect_equal(object = vcov(f2), expected = vcov(summary(f2)))
  testthat::expect_equal(object = nrow(vcov(f2)), expected = nrow(vcov(summary(f2))))
  testthat::expect_equal(object = ncol(vcov(f2)), expected = ncol(vcov(summary(f2))))
  testthat::expect_equal(object = nrow(vcov(f2)), expected = ncol(vcov(f2)))
  testthat::expect_equal(object = nrow(vcov(summary(f2))), expected = ncol(vcov(summary(f2))))
  testthat::expect_false(object = is.null(row.names(vcov(f2))))
  testthat::expect_false(object = is.null(colnames(vcov(f2))))
  testthat::expect_false(object = is.null(row.names(vcov(summary(f2)))))
  testthat::expect_false(object = is.null(colnames(vcov(summary(f2)))))
  testthat::expect_type(object = vcov(f2), type = "double")
  testthat::expect_type(object = vcov(summary(f2)), type = "double")
})

testthat::test_that("S3 method: logLik", {
  testthat::expect_equal(object = logLik(f1), expected = logLik(summary(f1)))
  testthat::expect_length(object = logLik(f1), n = 1)
  testthat::expect_length(object = logLik(summary(f1)), n = 1)
  testthat::expect_type(object = logLik(f1), type = "double")
  testthat::expect_type(object = logLik(summary(f1)), type = "double")

  testthat::expect_equal(object = logLik(f2), expected = logLik(summary(f2)))
  testthat::expect_length(object = logLik(f2), n = 1)
  testthat::expect_length(object = logLik(summary(f2)), n = 1)
  testthat::expect_type(object = logLik(f2), type = "double")
  testthat::expect_type(object = logLik(summary(f2)), type = "double")
})

