// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// exp_h
arma::vec exp_h(arma::mat const& X, arma::vec const& par);
RcppExport SEXP _streg_exp_h(SEXP XSEXP, SEXP parSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat const& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type par(parSEXP);
    rcpp_result_gen = Rcpp::wrap(exp_h(X, par));
    return rcpp_result_gen;
END_RCPP
}
// exp_surv
arma::vec exp_surv(arma::mat const& X, arma::vec const& t, arma::vec const& par);
RcppExport SEXP _streg_exp_surv(SEXP XSEXP, SEXP tSEXP, SEXP parSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat const& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type par(parSEXP);
    rcpp_result_gen = Rcpp::wrap(exp_surv(X, t, par));
    return rcpp_result_gen;
END_RCPP
}
// wei_h
arma::vec wei_h(arma::mat const& X, arma::vec const& t, arma::vec const& par);
RcppExport SEXP _streg_wei_h(SEXP XSEXP, SEXP tSEXP, SEXP parSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat const& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type par(parSEXP);
    rcpp_result_gen = Rcpp::wrap(wei_h(X, t, par));
    return rcpp_result_gen;
END_RCPP
}
// wei_surv
arma::vec wei_surv(arma::mat const& X, arma::vec const& t, arma::vec const& par);
RcppExport SEXP _streg_wei_surv(SEXP XSEXP, SEXP tSEXP, SEXP parSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat const& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type par(parSEXP);
    rcpp_result_gen = Rcpp::wrap(wei_surv(X, t, par));
    return rcpp_result_gen;
END_RCPP
}
// xb
arma::vec xb(arma::mat const& X, arma::vec const& par);
RcppExport SEXP _streg_xb(SEXP XSEXP, SEXP parSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat const& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type par(parSEXP);
    rcpp_result_gen = Rcpp::wrap(xb(X, par));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_streg_exp_h", (DL_FUNC) &_streg_exp_h, 2},
    {"_streg_exp_surv", (DL_FUNC) &_streg_exp_surv, 3},
    {"_streg_wei_h", (DL_FUNC) &_streg_wei_h, 3},
    {"_streg_wei_surv", (DL_FUNC) &_streg_wei_surv, 3},
    {"_streg_xb", (DL_FUNC) &_streg_xb, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_streg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
